name: test workflow 

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
       - name: Hello world
         run: echo "First GA job"

       - name: List files
         run: ls

       - name: Readme file
         run: cat README.md

